### ISSUE TITLE
upload.php failed?

### ISSUE THREAD

**Issue by StndrdTstr** [webdesigner97/musicXml2scratch#2]
I downloaded muxXml2scratch a couple of hours ago, and tried to convert two XML files into text.
The one that I got this particular error with was from here: https://musescore.com/user/868476/scores/548601

I assume this is not an error message, but it is just the raw PHP code in upload.php.
But, I do think that it is an error, as it did not show me a raw text file to copy into Scratch.

Here's what came up:

<?php
	$upload = $_FILES["mxlxml"];
	$start = microtime();
	
	//Check Mime Type
	if($upload["type"] == "text/xml")	{
		//It's XML
		$path = "tmp/" . $start;
		$contents = file_get_contents($upload["tmp_name"]);
		mkdir($path);
	}
	elseif(is_resource(zip_open($upload["tmp_name"])))	{
		//It's zipped
		//Unzip
		$path = "tmp/" . $start;
		$zip = new ZipArchive;
		$zip -> open($upload["tmp_name"]);
		$zip -> extractTo($path);
		//delete unused stuff
		unlink($path . "/META-INF/container.xml");
		rmdir($path . "/META-INF");
		//Get content
		$dir = scandir($path);
		$contents = file_get_contents($path . "/" . $dir[2]);
	}
	else	{
		//It's something else
		die("Invalid file");
	}
	//Files checked, content read. Now convert!
	require_once("lib/convert.php");
?>

**Comment by webdesigner97** [comment]
Did you run it on a webserver? Doesn't seem so. Try XAMPP ;)

**Comment by StndrdTstr** [comment]
How do I run it on a webserver? I just ran it from the folder...

**Comment by webdesigner97** [comment]
That won't work. Try XAMPP, it's free :)

**Comment by StndrdTstr** [comment]
What's XAMPP?

**Comment by webdesigner97** [comment]
Google is your friend :) It's a development Webserver.

**Comment by StndrdTstr** [comment]
But do I need a webserver to run it on?

**Comment by webdesigner97** [comment]
yes. A local one like XAMPP ill do fine. No need to buy one.

Am 09.03.2015 um 21:26 schrieb StndrdTstr:

**Comment by StndrdTstr** [comment]
im not sure how it can be a *local, web* server... is it broadcasting or not

**Comment by webdesigner97** [comment]
The XAMPP website has a lot of information about it. Have a look at it: https://www.apachefriends.org/index.html

**Comment by StndrdTstr** [comment]
ok, thanks
